name: marigold
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - accelerate>=0.22.0
  - diffusers>=0.25.0
  - matplotlib>=3.8.2
  - scipy>=1.11.4
  - python=3.10.12
  - pytorch=2.4.0
  - pytorch-cuda=11.7
  - torchvision=0.19.0
  - pip:
    - transformers>=4.32.1
