dataset:
  val:
  # - name: hypersim_depth
  #   disp_name: hypersim_depth_val
  #   dir: hypersim/hypersim_processed_val.tar
  #   filenames: data_split/hypersim_depth/filename_list_val_filtered.txt
  #   resize_to_hw:
  #   - 480
  #   - 640

  # - name: nyu_depth
  #   disp_name: nyu_depth_train_full
  #   dir: nyuv2/nyu_labeled_extracted.tar
  #   filenames: data_split/nyu_depth/labeled/filename_list_train.txt
  #   eigen_valid_mask: true

  # - name: kitti_depth
  #   disp_name: kitti_depth_val800_from_eigen_train
  #   dir: kitti/kitti_depth_sampled_val_800.tar
  #   filenames: data_split/kitti_depth/eigen_val_from_train_800.txt
  #   kitti_bm_crop: true
  #   valid_mask_crop: eigen

  # Smaller subsets for faster validation during training
  # The first dataset is used to calculate main eval metric.
  - name: hypersim_depth
    disp_name: hypersim_depth_val_small_80
    dir: hypersim/hypersim_processed_val.tar
    filenames: data_split/hypersim_depth/filename_list_val_filtered_small_80.txt
    resize_to_hw:
    - 480
    - 640

  - name: nyu_depth
    disp_name: nyu_depth_train_small_100
    dir: nyuv2/nyu_labeled_extracted.tar
    filenames: data_split/nyu_depth/labeled/filename_list_train_small_100.txt
    eigen_valid_mask: true

  - name: kitti_depth
    disp_name: kitti_depth_val_from_train_sub_100
    dir: kitti/kitti_sampled_val_800.tar
    filenames: data_split/kitti_depth/eigen_val_from_train_sub_100.txt
    kitti_bm_crop: true
    valid_mask_crop: eigen
